/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AArgumentDeclaration extends PArgumentDeclaration
{
    private TId _id_;
    private PVarTypeDeclaration _varTypeDeclaration_;

    public AArgumentDeclaration()
    {
        // Constructor
    }

    public AArgumentDeclaration(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PVarTypeDeclaration _varTypeDeclaration_)
    {
        // Constructor
        setId(_id_);

        setVarTypeDeclaration(_varTypeDeclaration_);

    }

    @Override
    public Object clone()
    {
        return new AArgumentDeclaration(
            cloneNode(this._id_),
            cloneNode(this._varTypeDeclaration_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArgumentDeclaration(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PVarTypeDeclaration getVarTypeDeclaration()
    {
        return this._varTypeDeclaration_;
    }

    public void setVarTypeDeclaration(PVarTypeDeclaration node)
    {
        if(this._varTypeDeclaration_ != null)
        {
            this._varTypeDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varTypeDeclaration_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._varTypeDeclaration_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._varTypeDeclaration_ == child)
        {
            this._varTypeDeclaration_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._varTypeDeclaration_ == oldChild)
        {
            setVarTypeDeclaration((PVarTypeDeclaration) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
