/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AClassDef extends PClassDef
{
    private TId _beginName_;
    private TId _extends_;
    private final LinkedList<PVarDeclaration> _varDeclaration_ = new LinkedList<PVarDeclaration>();
    private final LinkedList<PMethodDeclaration> _methodDeclaration_ = new LinkedList<PMethodDeclaration>();
    private TId _endName_;

    public AClassDef()
    {
        // Constructor
    }

    public AClassDef(
        @SuppressWarnings("hiding") TId _beginName_,
        @SuppressWarnings("hiding") TId _extends_,
        @SuppressWarnings("hiding") List<PVarDeclaration> _varDeclaration_,
        @SuppressWarnings("hiding") List<PMethodDeclaration> _methodDeclaration_,
        @SuppressWarnings("hiding") TId _endName_)
    {
        // Constructor
        setBeginName(_beginName_);

        setExtends(_extends_);

        setVarDeclaration(_varDeclaration_);

        setMethodDeclaration(_methodDeclaration_);

        setEndName(_endName_);

    }

    @Override
    public Object clone()
    {
        return new AClassDef(
            cloneNode(this._beginName_),
            cloneNode(this._extends_),
            cloneList(this._varDeclaration_),
            cloneList(this._methodDeclaration_),
            cloneNode(this._endName_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAClassDef(this);
    }

    public TId getBeginName()
    {
        return this._beginName_;
    }

    public void setBeginName(TId node)
    {
        if(this._beginName_ != null)
        {
            this._beginName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._beginName_ = node;
    }

    public TId getExtends()
    {
        return this._extends_;
    }

    public void setExtends(TId node)
    {
        if(this._extends_ != null)
        {
            this._extends_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._extends_ = node;
    }

    public LinkedList<PVarDeclaration> getVarDeclaration()
    {
        return this._varDeclaration_;
    }

    public void setVarDeclaration(List<PVarDeclaration> list)
    {
        this._varDeclaration_.clear();
        this._varDeclaration_.addAll(list);
        for(PVarDeclaration e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public LinkedList<PMethodDeclaration> getMethodDeclaration()
    {
        return this._methodDeclaration_;
    }

    public void setMethodDeclaration(List<PMethodDeclaration> list)
    {
        this._methodDeclaration_.clear();
        this._methodDeclaration_.addAll(list);
        for(PMethodDeclaration e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    public TId getEndName()
    {
        return this._endName_;
    }

    public void setEndName(TId node)
    {
        if(this._endName_ != null)
        {
            this._endName_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._endName_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._beginName_)
            + toString(this._extends_)
            + toString(this._varDeclaration_)
            + toString(this._methodDeclaration_)
            + toString(this._endName_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._beginName_ == child)
        {
            this._beginName_ = null;
            return;
        }

        if(this._extends_ == child)
        {
            this._extends_ = null;
            return;
        }

        if(this._varDeclaration_.remove(child))
        {
            return;
        }

        if(this._methodDeclaration_.remove(child))
        {
            return;
        }

        if(this._endName_ == child)
        {
            this._endName_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._beginName_ == oldChild)
        {
            setBeginName((TId) newChild);
            return;
        }

        if(this._extends_ == oldChild)
        {
            setExtends((TId) newChild);
            return;
        }

        for(ListIterator<PVarDeclaration> i = this._varDeclaration_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVarDeclaration) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PMethodDeclaration> i = this._methodDeclaration_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PMethodDeclaration) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        if(this._endName_ == oldChild)
        {
            setEndName((TId) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
