/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AConcatConcatExpression extends PConcatExpression
{
    private PConcatExpression _concatExpression_;
    private TConcatOp _concatOp_;
    private PAddExpression _addExpression_;

    public AConcatConcatExpression()
    {
        // Constructor
    }

    public AConcatConcatExpression(
        @SuppressWarnings("hiding") PConcatExpression _concatExpression_,
        @SuppressWarnings("hiding") TConcatOp _concatOp_,
        @SuppressWarnings("hiding") PAddExpression _addExpression_)
    {
        // Constructor
        setConcatExpression(_concatExpression_);

        setConcatOp(_concatOp_);

        setAddExpression(_addExpression_);

    }

    @Override
    public Object clone()
    {
        return new AConcatConcatExpression(
            cloneNode(this._concatExpression_),
            cloneNode(this._concatOp_),
            cloneNode(this._addExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAConcatConcatExpression(this);
    }

    public PConcatExpression getConcatExpression()
    {
        return this._concatExpression_;
    }

    public void setConcatExpression(PConcatExpression node)
    {
        if(this._concatExpression_ != null)
        {
            this._concatExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concatExpression_ = node;
    }

    public TConcatOp getConcatOp()
    {
        return this._concatOp_;
    }

    public void setConcatOp(TConcatOp node)
    {
        if(this._concatOp_ != null)
        {
            this._concatOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concatOp_ = node;
    }

    public PAddExpression getAddExpression()
    {
        return this._addExpression_;
    }

    public void setAddExpression(PAddExpression node)
    {
        if(this._addExpression_ != null)
        {
            this._addExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._concatExpression_)
            + toString(this._concatOp_)
            + toString(this._addExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._concatExpression_ == child)
        {
            this._concatExpression_ = null;
            return;
        }

        if(this._concatOp_ == child)
        {
            this._concatOp_ = null;
            return;
        }

        if(this._addExpression_ == child)
        {
            this._addExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._concatExpression_ == oldChild)
        {
            setConcatExpression((PConcatExpression) newChild);
            return;
        }

        if(this._concatOp_ == oldChild)
        {
            setConcatOp((TConcatOp) newChild);
            return;
        }

        if(this._addExpression_ == oldChild)
        {
            setAddExpression((PAddExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
