/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AExpr3RelationalExpression extends PRelationalExpression
{
    private PConcatExpression _concatExpression_;

    public AExpr3RelationalExpression()
    {
        // Constructor
    }

    public AExpr3RelationalExpression(
        @SuppressWarnings("hiding") PConcatExpression _concatExpression_)
    {
        // Constructor
        setConcatExpression(_concatExpression_);

    }

    @Override
    public Object clone()
    {
        return new AExpr3RelationalExpression(
            cloneNode(this._concatExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpr3RelationalExpression(this);
    }

    public PConcatExpression getConcatExpression()
    {
        return this._concatExpression_;
    }

    public void setConcatExpression(PConcatExpression node)
    {
        if(this._concatExpression_ != null)
        {
            this._concatExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._concatExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._concatExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._concatExpression_ == child)
        {
            this._concatExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._concatExpression_ == oldChild)
        {
            setConcatExpression((PConcatExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
