/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AExpr8GroupObjectCallExpression extends PGroupObjectCallExpression
{
    private PObjectCallExpression _objectCallExpression_;

    public AExpr8GroupObjectCallExpression()
    {
        // Constructor
    }

    public AExpr8GroupObjectCallExpression(
        @SuppressWarnings("hiding") PObjectCallExpression _objectCallExpression_)
    {
        // Constructor
        setObjectCallExpression(_objectCallExpression_);

    }

    @Override
    public Object clone()
    {
        return new AExpr8GroupObjectCallExpression(
            cloneNode(this._objectCallExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpr8GroupObjectCallExpression(this);
    }

    public PObjectCallExpression getObjectCallExpression()
    {
        return this._objectCallExpression_;
    }

    public void setObjectCallExpression(PObjectCallExpression node)
    {
        if(this._objectCallExpression_ != null)
        {
            this._objectCallExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objectCallExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objectCallExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objectCallExpression_ == child)
        {
            this._objectCallExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objectCallExpression_ == oldChild)
        {
            setObjectCallExpression((PObjectCallExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
