/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AExpr10CallExpression extends PCallExpression
{
    private PRealExpression _realExpression_;

    public AExpr10CallExpression()
    {
        // Constructor
    }

    public AExpr10CallExpression(
        @SuppressWarnings("hiding") PRealExpression _realExpression_)
    {
        // Constructor
        setRealExpression(_realExpression_);

    }

    @Override
    public Object clone()
    {
        return new AExpr10CallExpression(
            cloneNode(this._realExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpr10CallExpression(this);
    }

    public PRealExpression getRealExpression()
    {
        return this._realExpression_;
    }

    public void setRealExpression(PRealExpression node)
    {
        if(this._realExpression_ != null)
        {
            this._realExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._realExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._realExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._realExpression_ == child)
        {
            this._realExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._realExpression_ == oldChild)
        {
            setRealExpression((PRealExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
