/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AExpr4ConcatExpression extends PConcatExpression
{
    private PAddExpression _addExpression_;

    public AExpr4ConcatExpression()
    {
        // Constructor
    }

    public AExpr4ConcatExpression(
        @SuppressWarnings("hiding") PAddExpression _addExpression_)
    {
        // Constructor
        setAddExpression(_addExpression_);

    }

    @Override
    public Object clone()
    {
        return new AExpr4ConcatExpression(
            cloneNode(this._addExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpr4ConcatExpression(this);
    }

    public PAddExpression getAddExpression()
    {
        return this._addExpression_;
    }

    public void setAddExpression(PAddExpression node)
    {
        if(this._addExpression_ != null)
        {
            this._addExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._addExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._addExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._addExpression_ == child)
        {
            this._addExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._addExpression_ == oldChild)
        {
            setAddExpression((PAddExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
