/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AGroupGroupObjectCallExpression extends PGroupObjectCallExpression
{
    private PGroupExpression _groupExpression_;

    public AGroupGroupObjectCallExpression()
    {
        // Constructor
    }

    public AGroupGroupObjectCallExpression(
        @SuppressWarnings("hiding") PGroupExpression _groupExpression_)
    {
        // Constructor
        setGroupExpression(_groupExpression_);

    }

    @Override
    public Object clone()
    {
        return new AGroupGroupObjectCallExpression(
            cloneNode(this._groupExpression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAGroupGroupObjectCallExpression(this);
    }

    public PGroupExpression getGroupExpression()
    {
        return this._groupExpression_;
    }

    public void setGroupExpression(PGroupExpression node)
    {
        if(this._groupExpression_ != null)
        {
            this._groupExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._groupExpression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._groupExpression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._groupExpression_ == child)
        {
            this._groupExpression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._groupExpression_ == oldChild)
        {
            setGroupExpression((PGroupExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
