/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AObjectCallStatement extends PCallStatement
{
    private PObjectCallExpression _objectCallExpression_;
    private PObjectCall _objectCall_;

    public AObjectCallStatement()
    {
        // Constructor
    }

    public AObjectCallStatement(
        @SuppressWarnings("hiding") PObjectCallExpression _objectCallExpression_,
        @SuppressWarnings("hiding") PObjectCall _objectCall_)
    {
        // Constructor
        setObjectCallExpression(_objectCallExpression_);

        setObjectCall(_objectCall_);

    }

    @Override
    public Object clone()
    {
        return new AObjectCallStatement(
            cloneNode(this._objectCallExpression_),
            cloneNode(this._objectCall_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAObjectCallStatement(this);
    }

    public PObjectCallExpression getObjectCallExpression()
    {
        return this._objectCallExpression_;
    }

    public void setObjectCallExpression(PObjectCallExpression node)
    {
        if(this._objectCallExpression_ != null)
        {
            this._objectCallExpression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objectCallExpression_ = node;
    }

    public PObjectCall getObjectCall()
    {
        return this._objectCall_;
    }

    public void setObjectCall(PObjectCall node)
    {
        if(this._objectCall_ != null)
        {
            this._objectCall_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._objectCall_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._objectCallExpression_)
            + toString(this._objectCall_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._objectCallExpression_ == child)
        {
            this._objectCallExpression_ = null;
            return;
        }

        if(this._objectCall_ == child)
        {
            this._objectCall_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._objectCallExpression_ == oldChild)
        {
            setObjectCallExpression((PObjectCallExpression) newChild);
            return;
        }

        if(this._objectCall_ == oldChild)
        {
            setObjectCall((PObjectCall) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
