/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class ARelationalRelationalExpression extends PRelationalExpression
{
    private PConcatExpression _first_;
    private PRelationalOperator _relationalOperator_;
    private PConcatExpression _second_;

    public ARelationalRelationalExpression()
    {
        // Constructor
    }

    public ARelationalRelationalExpression(
        @SuppressWarnings("hiding") PConcatExpression _first_,
        @SuppressWarnings("hiding") PRelationalOperator _relationalOperator_,
        @SuppressWarnings("hiding") PConcatExpression _second_)
    {
        // Constructor
        setFirst(_first_);

        setRelationalOperator(_relationalOperator_);

        setSecond(_second_);

    }

    @Override
    public Object clone()
    {
        return new ARelationalRelationalExpression(
            cloneNode(this._first_),
            cloneNode(this._relationalOperator_),
            cloneNode(this._second_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARelationalRelationalExpression(this);
    }

    public PConcatExpression getFirst()
    {
        return this._first_;
    }

    public void setFirst(PConcatExpression node)
    {
        if(this._first_ != null)
        {
            this._first_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._first_ = node;
    }

    public PRelationalOperator getRelationalOperator()
    {
        return this._relationalOperator_;
    }

    public void setRelationalOperator(PRelationalOperator node)
    {
        if(this._relationalOperator_ != null)
        {
            this._relationalOperator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._relationalOperator_ = node;
    }

    public PConcatExpression getSecond()
    {
        return this._second_;
    }

    public void setSecond(PConcatExpression node)
    {
        if(this._second_ != null)
        {
            this._second_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._second_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._first_)
            + toString(this._relationalOperator_)
            + toString(this._second_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._first_ == child)
        {
            this._first_ = null;
            return;
        }

        if(this._relationalOperator_ == child)
        {
            this._relationalOperator_ = null;
            return;
        }

        if(this._second_ == child)
        {
            this._second_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._first_ == oldChild)
        {
            setFirst((PConcatExpression) newChild);
            return;
        }

        if(this._relationalOperator_ == oldChild)
        {
            setRelationalOperator((PRelationalOperator) newChild);
            return;
        }

        if(this._second_ == oldChild)
        {
            setSecond((PConcatExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
