/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AStatementList extends PStatementList
{
    private final LinkedList<PStatementHead> _statementHead_ = new LinkedList<PStatementHead>();

    public AStatementList()
    {
        // Constructor
    }

    public AStatementList(
        @SuppressWarnings("hiding") List<PStatementHead> _statementHead_)
    {
        // Constructor
        setStatementHead(_statementHead_);

    }

    @Override
    public Object clone()
    {
        return new AStatementList(
            cloneList(this._statementHead_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStatementList(this);
    }

    public LinkedList<PStatementHead> getStatementHead()
    {
        return this._statementHead_;
    }

    public void setStatementHead(List<PStatementHead> list)
    {
        this._statementHead_.clear();
        this._statementHead_.addAll(list);
        for(PStatementHead e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._statementHead_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._statementHead_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PStatementHead> i = this._statementHead_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PStatementHead) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
