/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AVarInstantiation extends PVarInstantiation
{
    private TAssignmentOp _assignmentOp_;
    private PExpression _expression_;

    public AVarInstantiation()
    {
        // Constructor
    }

    public AVarInstantiation(
        @SuppressWarnings("hiding") TAssignmentOp _assignmentOp_,
        @SuppressWarnings("hiding") PExpression _expression_)
    {
        // Constructor
        setAssignmentOp(_assignmentOp_);

        setExpression(_expression_);

    }

    @Override
    public Object clone()
    {
        return new AVarInstantiation(
            cloneNode(this._assignmentOp_),
            cloneNode(this._expression_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarInstantiation(this);
    }

    public TAssignmentOp getAssignmentOp()
    {
        return this._assignmentOp_;
    }

    public void setAssignmentOp(TAssignmentOp node)
    {
        if(this._assignmentOp_ != null)
        {
            this._assignmentOp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._assignmentOp_ = node;
    }

    public PExpression getExpression()
    {
        return this._expression_;
    }

    public void setExpression(PExpression node)
    {
        if(this._expression_ != null)
        {
            this._expression_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expression_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._assignmentOp_)
            + toString(this._expression_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._assignmentOp_ == child)
        {
            this._assignmentOp_ = null;
            return;
        }

        if(this._expression_ == child)
        {
            this._expression_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._assignmentOp_ == oldChild)
        {
            setAssignmentOp((TAssignmentOp) newChild);
            return;
        }

        if(this._expression_ == oldChild)
        {
            setExpression((PExpression) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
