/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import java.util.*;
import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class AVarDeclaration extends PVarDeclaration
{
    private TId _id_;
    private PVarTypeDeclaration _varTypeDeclaration_;
    private PVarInstantiation _varInstantiation_;
    private final LinkedList<TEol> _eol_ = new LinkedList<TEol>();

    public AVarDeclaration()
    {
        // Constructor
    }

    public AVarDeclaration(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") PVarTypeDeclaration _varTypeDeclaration_,
        @SuppressWarnings("hiding") PVarInstantiation _varInstantiation_,
        @SuppressWarnings("hiding") List<TEol> _eol_)
    {
        // Constructor
        setId(_id_);

        setVarTypeDeclaration(_varTypeDeclaration_);

        setVarInstantiation(_varInstantiation_);

        setEol(_eol_);

    }

    @Override
    public Object clone()
    {
        return new AVarDeclaration(
            cloneNode(this._id_),
            cloneNode(this._varTypeDeclaration_),
            cloneNode(this._varInstantiation_),
            cloneList(this._eol_));
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVarDeclaration(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public PVarTypeDeclaration getVarTypeDeclaration()
    {
        return this._varTypeDeclaration_;
    }

    public void setVarTypeDeclaration(PVarTypeDeclaration node)
    {
        if(this._varTypeDeclaration_ != null)
        {
            this._varTypeDeclaration_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varTypeDeclaration_ = node;
    }

    public PVarInstantiation getVarInstantiation()
    {
        return this._varInstantiation_;
    }

    public void setVarInstantiation(PVarInstantiation node)
    {
        if(this._varInstantiation_ != null)
        {
            this._varInstantiation_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._varInstantiation_ = node;
    }

    public LinkedList<TEol> getEol()
    {
        return this._eol_;
    }

    public void setEol(List<TEol> list)
    {
        this._eol_.clear();
        this._eol_.addAll(list);
        for(TEol e : list)
        {
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._varTypeDeclaration_)
            + toString(this._varInstantiation_)
            + toString(this._eol_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._varTypeDeclaration_ == child)
        {
            this._varTypeDeclaration_ = null;
            return;
        }

        if(this._varInstantiation_ == child)
        {
            this._varInstantiation_ = null;
            return;
        }

        if(this._eol_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        if(this._varTypeDeclaration_ == oldChild)
        {
            setVarTypeDeclaration((PVarTypeDeclaration) newChild);
            return;
        }

        if(this._varInstantiation_ == oldChild)
        {
            setVarInstantiation((PVarInstantiation) newChild);
            return;
        }

        for(ListIterator<TEol> i = this._eol_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((TEol) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
