/* This file was generated by SableCC (http://www.sablecc.org/). */

package cps450.oodle.node;

import cps450.oodle.analysis.*;

@SuppressWarnings("nls")
public final class TIs extends Token
{
    public TIs()
    {
        super.setText("is");
    }

    public TIs(int line, int pos)
    {
        super.setText("is");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TIs(getLine(), getPos());
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTIs(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TIs text.");
    }
}
